service: campeonato-manager

configValidationMode: off

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  stage: ${opt:stage, 'dev'}

  deploymentBucket:
    name: campeonato-manager-deployment-bucket
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

  environment:
    NODE_ENV: ${self:provider.stage}
    MONGO_URI: ${env:MONGO_URI}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
            - apigateway:*
            - logs:*
            - iam:PassRole
            - s3:*
          Resource: '*'

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: true

build:
  esbuild: false

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node18
    platform: node
    concurrency: 10

functions:
  startMatch:
    handler: src/presentation/lambdas/startMatchHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/start
          method: POST

  startSecondHalf:
    handler: src/presentation/lambdas/startSecondHalfHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/start-second-half
          method: POST

  closeMatch:
    handler: src/presentation/lambdas/closeMatchHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/close
          method: POST

  registerEvent:
    handler: src/presentation/lambdas/registerMatchEventHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/events
          method: POST

  voteCraque:
    handler: src/presentation/lambdas/voteCraqueDaPartidaHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/vote
          method: POST

  syncOfflineData:
    handler: src/presentation/lambdas/syncOfflineDataHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/sync-offline
          method: POST

  getClassification:
    handler: src/presentation/lambdas/getClassificationHandler.handler
    events:
      - httpApi:
          path: /classification
          method: GET

  getTopScorers:
    handler: src/presentation/lambdas/getTopScorersHandler.handler
    events:
      - httpApi:
          path: /top-scorers
          method: GET

  getBestGoalkeeper:
    handler: src/presentation/lambdas/getBestGoalkeeperHandler.handler
    events:
      - httpApi:
          path: /best-goalkeepers
          method: GET

  getPublicMatchDetails:
    handler: src/presentation/lambdas/getPublicMatchDetailsHandler.handler
    events:
      - httpApi:
          path: /matches/{matchId}/details
          method: GET

  getMatchesTable:
    handler: src/presentation/lambdas/getMatchesTableHandler.handler
    events:
      - httpApi:
          path: /matches-table
          method: GET
