service: campeonato-manager

configValidationMode: off

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 512
  timeout: 30
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    MONGO_URI: ${env:MONGO_URI}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:*
            - apigateway:*
            - logs:*
            - iam:PassRole
          Resource: '*'

build:
  esbuild: false

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: node18
    platform: node
    concurrency: 10

functions:
  startMatch:
    handler: src/presentation/lambdas/startMatchHandler.handler
    events:
      - http:
          path: matches/{matchId}/start
          method: post

  startSecondHalf:
    handler: src/presentation/lambdas/startSecondHalfHandler.handler
    events:
      - http:
          path: matches/{matchId}/start-second-half
          method: post

  closeMatch:
    handler: src/presentation/lambdas/closeMatchHandler.handler
    events:
      - http:
          path: matches/{matchId}/close
          method: post

  registerEvent:
    handler: src/presentation/lambdas/registerMatchEventHandler.handler
    events:
      - http:
          path: matches/{matchId}/events
          method: post

  voteCraque:
    handler: src/presentation/lambdas/voteCraqueDaPartidaHandler.handler
    events:
      - http:
          path: matches/{matchId}/vote
          method: post

  syncOfflineData:
    handler: src/presentation/lambdas/syncOfflineDataHandler.handler
    events:
      - http:
          path: matches/{matchId}/sync-offline
          method: post

  getClassification:
    handler: src/presentation/lambdas/getClassificationHandler.handler
    events:
      - http:
          path: classification
          method: get

  getTopScorers:
    handler: src/presentation/lambdas/getTopScorersHandler.handler
    events:
      - http:
          path: top-scorers
          method: get

  getBestGoalkeeper:
    handler: src/presentation/lambdas/getBestGoalkeeperHandler.handler
    events:
      - http:
          path: best-goalkeeper
          method: get

  getPublicMatchDetails:
    handler: src/presentation/lambdas/getPublicMatchDetailsHandler.handler
    events:
      - http:
          path: matches/{matchId}/details
          method: get

  getMatchesTable:
    handler: src/presentation/lambdas/getMatchesTableHandler.handler
    events:
      - http:
          path: matches-table
          method: get
